### ISSUE TITLE
COntacting support link is broken

### ISSUE THREAD

**Issue by MicheleNicosia** [ibm-cloud-docs/mass-data-migration#1]
Hi Team,
 i'm searching for support on the MDM device, trough the page here COntacting support from here: 
https://cloud.ibm.com/docs/mass-data-migration?topic=mass-data-migration-troubleshooting

and this link is broken:  https://cloud.ibm.com/docs/get-support?topic=get-support-getting-customer-support

Thank you

**Comment by KentHall2018** [comment]
repo is being deprecated
